In [1]:
import pandas as pd
df_1 = pd.read_csv('ar41_for_ulb.csv', sep=';')

In [2]:
df_1.drop('Unnamed: 0', axis=1, inplace=True)

In [6]:
df_1['timestamps_UTC'] = pd.to_datetime(df_1['timestamps_UTC'])
df_1['date_hour'] = df_1['timestamps_UTC'].dt.to_period('H')

In [8]:
df_1

,mapped_veh_id,timestamps_UTC,lat,lon,RS_E_InAirTemp_PC1,RS_E_InAirTemp_PC2,RS_E_OilPress_PC1,RS_E_OilPress_PC2,RS_E_RPM_PC1,RS_E_RPM_PC2,RS_E_WatTemp_PC1,RS_E_WatTemp_PC2,RS_T_OilTemp_PC1,RS_T_OilTemp_PC2,date_hour
0,181.0,2023-08-01 03:44:12,50.769818,3.872114,27.0,23.0,255.0,238.0,794.0,801.0,83.0,81.0,76.0,77.0,2023-08-01 03:00
1,143.0,2023-08-01 06:36:29,51.039993,3.693429,33.0,32.0,272.0,324.0,802.0,804.0,78.0,78.0,73.0,74.0,2023-08-01 06:00
2,183.0,2023-08-24 06:53:54,50.742203,3.602035,31.0,33.0,234.0,182.0,799.0,802.0,82.0,82.0,85.0,87.0,2023-08-24 06:00
3,177.0,2023-08-01 13:53:38,50.930914,5.327132,35.0,38.0,220.0,244.0,794.0,801.0,77.0,81.0,78.0,82.0,2023-08-01 13:00
4,143.0,2023-08-24 07:02:30,51.180773,3.575259,41.0,34.0,227.0,282.0,806.0,800.0,85.0,78.0,82.0,79.0,2023-08-24 07:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17679268,180.0,2023-05-28 19:28:59,50.919864,3.791125,40.0,36.0,238.0,238.0,800.0,797.0,86.0,86.0,90.0,92.0,2023-05-28 19:00
17679269,180.0,2023-05-28 19:54:41,51.035243,3.710695,41.0,31.0,244.0,241.0,790.0,801.0,86.0,87.0,87.0,87.0,2023-05-28 19:00
17679270,122.0,2023-05-28 20:23:20,51.015686,3.775316,52.0,42.0,3.0,3.0,0.0,0.0,78.0,82.0,80.0,82.0,2023-05-28 20:00
17679271,177.0,2023-05-28 20:46:00,51.189586,5.109380,27.0,38.0,417.0,469.0,1441.0,1454.0,77.0,78.0,76.0,80.0,2023-05-28 20:00
17679272,110.0,2023-05-28 21:05:24,51.041178,3.683947,37.0,33.0,220.0,196.0,805.0,796.0,83.0,81.0,79.0,75.0,2023-05-28 21:00

In [10]:
# splitting date and time components into separate columns
df_1['date'] = df_1['date_hour'].dt.strftime('%Y-%m-%d')
df_1['hour'] = df_1['date_hour'].dt.strftime('%H:%M')

In [13]:
df_2 = pd.read_csv('ar41_for_ulb_round.csv')
df_2

,mapped_veh_id,date_hour,lat,lon,temp,main_feels_like,main_pressure,main_humidity,main_temp_min,main_temp_max,wind_speed,wind_deg,wind_gust,clouds_all,weather_id,weather_main,weather_description,weather_icon
0,102.0,2023-01-23 07:00:00,51.0163,3.7728,274.53,271.79,1035.0,92.0,273.98,274.94,2.47,40.0,6.61,100.0,804.0,Clouds,overcast clouds,04n
1,102.0,2023-01-23 14:00:00,51.0156,3.7744,276.79,273.16,1035.0,74.0,275.96,277.71,4.31,69.0,6.21,84.0,803.0,Clouds,broken clouds,04d
2,102.0,2023-01-23 15:00:00,51.0202,3.7624,276.69,273.08,1035.0,75.0,276.20,277.67,4.22,67.0,6.50,83.0,803.0,Clouds,broken clouds,04d
3,102.0,2023-01-23 16:00:00,51.0606,3.7044,276.49,272.69,1036.0,75.0,275.62,277.14,4.48,63.0,7.02,86.0,804.0,Clouds,overcast clouds,04d
4,102.0,2023-01-23 17:00:00,51.0968,3.6750,276.29,272.71,1036.0,86.0,275.50,277.11,4.02,66.0,7.14,85.0,804.0,Clouds,overcast clouds,04n
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208273,197.0,2023-09-13 13:00:00,50.1945,4.4762,293.54,293.62,1019.0,76.0,292.51,294.90,3.60,270.0,NaN,40.0,802.0,Clouds,scattered clouds,03d
208274,197.0,2023-09-13 14:00:00,50.3437,4.4300,293.80,293.67,1019.0,67.0,291.62,295.69,3.60,270.0,NaN,40.0,802.0,Clouds,scattered clouds,03d
208275,197.0,2023-09-13 15:00:00,50.0871,4.5028,292.57,292.58,1020.0,77.0,292.51,293.79,6.17,10.0,NaN,40.0,802.0,Clouds,scattered clouds,03d
208276,197.0,2023-09-13 16:00:00,50.1764,4.4951,292.41,292.27,1020.0,72.0,291.90,292.67,5.66,20.0,NaN,75.0,803.0,Clouds,broken clouds,04d
208277,197.0,2023-09-13 17:00:00,50.3771,4.4200,292.10,291.93,1020.0,72.0,291.42,292.96,4.12,50.0,NaN,20.0,801.0,Clouds,few clouds,02d

In [16]:
df_2['date_hour'] = pd.to_datetime(df_2['date_hour'])

In [17]:
# splitting date and time components into separate columns
df_2['date'] = df_2['date_hour'].dt.strftime('%Y-%m-%d')
df_2['hour'] = df_2['date_hour'].dt.strftime('%H:%M')

In [18]:
df_2

,mapped_veh_id,date_hour,lat,lon,temp,main_feels_like,main_pressure,main_humidity,main_temp_min,main_temp_max,wind_speed,wind_deg,wind_gust,clouds_all,weather_id,weather_main,weather_description,weather_icon,date,hour
0,102.0,2023-01-23 07:00:00,51.0163,3.7728,274.53,271.79,1035.0,92.0,273.98,274.94,2.47,40.0,6.61,100.0,804.0,Clouds,overcast clouds,04n,2023-01-23,07:00
1,102.0,2023-01-23 14:00:00,51.0156,3.7744,276.79,273.16,1035.0,74.0,275.96,277.71,4.31,69.0,6.21,84.0,803.0,Clouds,broken clouds,04d,2023-01-23,14:00
2,102.0,2023-01-23 15:00:00,51.0202,3.7624,276.69,273.08,1035.0,75.0,276.20,277.67,4.22,67.0,6.50,83.0,803.0,Clouds,broken clouds,04d,2023-01-23,15:00
3,102.0,2023-01-23 16:00:00,51.0606,3.7044,276.49,272.69,1036.0,75.0,275.62,277.14,4.48,63.0,7.02,86.0,804.0,Clouds,overcast clouds,04d,2023-01-23,16:00
4,102.0,2023-01-23 17:00:00,51.0968,3.6750,276.29,272.71,1036.0,86.0,275.50,277.11,4.02,66.0,7.14,85.0,804.0,Clouds,overcast clouds,04n,2023-01-23,17:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208273,197.0,2023-09-13 13:00:00,50.1945,4.4762,293.54,293.62,1019.0,76.0,292.51,294.90,3.60,270.0,NaN,40.0,802.0,Clouds,scattered clouds,03d,2023-09-13,13:00
208274,197.0,2023-09-13 14:00:00,50.3437,4.4300,293.80,293.67,1019.0,67.0,291.62,295.69,3.60,270.0,NaN,40.0,802.0,Clouds,scattered clouds,03d,2023-09-13,14:00
208275,197.0,2023-09-13 15:00:00,50.0871,4.5028,292.57,292.58,1020.0,77.0,292.51,293.79,6.17,10.0,NaN,40.0,802.0,Clouds,scattered clouds,03d,2023-09-13,15:00
208276,197.0,2023-09-13 16:00:00,50.1764,4.4951,292.41,292.27,1020.0,72.0,291.90,292.67,5.66,20.0,NaN,75.0,803.0,Clouds,broken clouds,04d,2023-09-13,16:00
208277,197.0,2023-09-13 17:00:00,50.3771,4.4200,292.10,291.93,1020.0,72.0,291.42,292.96,4.12,50.0,NaN,20.0,801.0,Clouds,few clouds,02d,2023-09-13,17:00

In [20]:
merged_df = pd.merge(df_1, df_2, on=['mapped_veh_id', 'date', 'hour'], how='left')
merged_df

,mapped_veh_id,timestamps_UTC,lat_x,lon_x,RS_E_InAirTemp_PC1,RS_E_InAirTemp_PC2,RS_E_OilPress_PC1,RS_E_OilPress_PC2,RS_E_RPM_PC1,RS_E_RPM_PC2,...,main_temp_min,main_temp_max,wind_speed,wind_deg,wind_gust,clouds_all,weather_id,weather_main,weather_description,weather_icon
0,181.0,2023-08-01 03:44:12,50.769818,3.872114,27.0,23.0,255.0,238.0,794.0,801.0,...,287.64,288.74,5.89,255.0,12.99,97.0,804.0,Clouds,overcast clouds,04n
1,143.0,2023-08-01 06:36:29,51.039993,3.693429,33.0,32.0,272.0,324.0,802.0,804.0,...,288.09,289.32,5.27,251.0,10.46,56.0,803.0,Clouds,broken clouds,04d
2,183.0,2023-08-24 06:53:54,50.742203,3.602035,31.0,33.0,234.0,182.0,799.0,802.0,...,290.32,292.38,1.34,80.0,2.68,95.0,804.0,Clouds,overcast clouds,04d
3,177.0,2023-08-01 13:53:38,50.930914,5.327132,35.0,38.0,220.0,244.0,794.0,801.0,...,292.08,294.83,6.17,270.0,NaN,75.0,803.0,Clouds,broken clouds,04d
4,143.0,2023-08-24 07:02:30,51.180773,3.575259,41.0,34.0,227.0,282.0,806.0,800.0,...,291.57,294.29,2.04,125.0,3.65,100.0,804.0,Clouds,overcast clouds,04d
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17679268,180.0,2023-05-28 19:28:59,50.919864,3.791125,40.0,36.0,238.0,238.0,800.0,797.0,...,288.59,293.73,6.02,33.0,10.80,51.0,803.0,Clouds,broken clouds,04d
17679269,180.0,2023-05-28 19:54:41,51.035243,3.710695,41.0,31.0,244.0,241.0,790.0,801.0,...,288.59,293.73,6.02,33.0,10.80,51.0,803.0,Clouds,broken clouds,04d
17679270,122.0,2023-05-28 20:23:20,51.015686,3.775316,52.0,42.0,3.0,3.0,0.0,0.0,...,287.09,291.20,6.20,33.0,11.94,39.0,802.0,Clouds,scattered clouds,03n
17679271,177.0,2023-05-28 20:46:00,51.189586,5.109380,27.0,38.0,417.0,469.0,1441.0,1454.0,...,288.99,292.29,6.21,33.0,12.24,19.0,801.0,Clouds,few clouds,02n
17679272,110.0,2023-05-28 21:05:24,51.041178,3.683947,37.0,33.0,220.0,196.0,805.0,796.0,...,286.53,290.19,6.72,36.0,13.00,32.0,802.0,Clouds,scattered clouds,03n

In [21]:
merged_df.to_csv('ar41_for_ulb.csv', index=False)

In [36]:
columns_before_temp = merged_df.loc[:, :'temp']
specified_columns = merged_df[['weather_main', 'weather_description']]
final_df = pd.concat([columns_before_temp, specified_columns], axis=1)

In [34]:
merged_df.columns  #temp, weather_main, 'weather_description', 'elevation'

Index(['mapped_veh_id', 'timestamps_UTC', 'lat_x', 'lon_x',
       'RS_E_InAirTemp_PC1', 'RS_E_InAirTemp_PC2', 'RS_E_OilPress_PC1',
       'RS_E_OilPress_PC2', 'RS_E_RPM_PC1', 'RS_E_RPM_PC2', 'RS_E_WatTemp_PC1',
       'RS_E_WatTemp_PC2', 'RS_T_OilTemp_PC1', 'RS_T_OilTemp_PC2',
       'date_hour_x', 'date', 'hour', 'date_hour_y', 'lat_y', 'lon_y', 'temp',
       'main_feels_like', 'main_pressure', 'main_humidity', 'main_temp_min',
       'main_temp_max', 'wind_speed', 'wind_deg', 'wind_gust', 'clouds_all',
       'weather_id', 'weather_main', 'weather_description', 'weather_icon',
       'lat', 'lon'],
      dtype='object')

In [38]:
# Change datatypes
final_df['temp'] = final_df['temp'].astype('Float32')

# Rename 'weather_main' to 'weather'
final_df.rename(columns={'weather_main': 'weather'}, inplace=True)

In [22]:
df_3 = pd.read_csv('elevation.csv')

In [39]:
final_df

,mapped_veh_id,timestamps_UTC,lat_x,lon_x,RS_E_InAirTemp_PC1,RS_E_InAirTemp_PC2,RS_E_OilPress_PC1,RS_E_OilPress_PC2,RS_E_RPM_PC1,RS_E_RPM_PC2,...,RS_T_OilTemp_PC2,date_hour_x,date,hour,date_hour_y,lat_y,lon_y,temp,weather,weather_description
0,181.0,2023-08-01 03:44:12,50.769818,3.872114,27.0,23.0,255.0,238.0,794.0,801.0,...,77.0,2023-08-01 03:00,2023-08-01,03:00,2023-08-01 03:00:00,50.7696,3.8720,288.190002,Clouds,overcast clouds
1,143.0,2023-08-01 06:36:29,51.039993,3.693429,33.0,32.0,272.0,324.0,802.0,804.0,...,74.0,2023-08-01 06:00,2023-08-01,06:00,2023-08-01 06:00:00,51.0392,3.6966,288.709991,Clouds,broken clouds
2,183.0,2023-08-24 06:53:54,50.742203,3.602035,31.0,33.0,234.0,182.0,799.0,802.0,...,87.0,2023-08-24 06:00,2023-08-24,06:00,2023-08-24 06:00:00,50.8538,3.6208,291.380005,Clouds,overcast clouds
3,177.0,2023-08-01 13:53:38,50.930914,5.327132,35.0,38.0,220.0,244.0,794.0,801.0,...,82.0,2023-08-01 13:00,2023-08-01,13:00,2023-08-01 13:00:00,51.0544,5.2561,293.589996,Clouds,broken clouds
4,143.0,2023-08-24 07:02:30,51.180773,3.575259,41.0,34.0,227.0,282.0,806.0,800.0,...,79.0,2023-08-24 07:00,2023-08-24,07:00,2023-08-24 07:00:00,51.0994,3.6720,292.709991,Clouds,overcast clouds
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17679268,180.0,2023-05-28 19:28:59,50.919864,3.791125,40.0,36.0,238.0,238.0,800.0,797.0,...,92.0,2023-05-28 19:00,2023-05-28,19:00,2023-05-28 19:00:00,50.9202,3.7960,290.230011,Clouds,broken clouds
17679269,180.0,2023-05-28 19:54:41,51.035243,3.710695,41.0,31.0,244.0,241.0,790.0,801.0,...,87.0,2023-05-28 19:00,2023-05-28,19:00,2023-05-28 19:00:00,50.9202,3.7960,290.230011,Clouds,broken clouds
17679270,122.0,2023-05-28 20:23:20,51.015686,3.775316,52.0,42.0,3.0,3.0,0.0,0.0,...,82.0,2023-05-28 20:00,2023-05-28,20:00,2023-05-28 20:00:00,51.0227,3.7524,288.809998,Clouds,scattered clouds
17679271,177.0,2023-05-28 20:46:00,51.189586,5.109380,27.0,38.0,417.0,469.0,1441.0,1454.0,...,80.0,2023-05-28 20:00,2023-05-28,20:00,2023-05-28 20:00:00,51.1571,5.1562,291.420013,Clouds,few clouds
17679272,110.0,2023-05-28 21:05:24,51.041178,3.683947,37.0,33.0,220.0,196.0,805.0,796.0,...,75.0,2023-05-28 21:00,2023-05-28,21:00,2023-05-28 21:00:00,51.0256,3.7420,287.820007,Clouds,scattered clouds

In [26]:
df_3['lat'] = df_3['cell_lat']
df_3['lon'] = df_3['cell_lon']

NameError: name 'df' is not defined

In [32]:
merged_df

,mapped_veh_id,timestamps_UTC,lat_x,lon_x,RS_E_InAirTemp_PC1,RS_E_InAirTemp_PC2,RS_E_OilPress_PC1,RS_E_OilPress_PC2,RS_E_RPM_PC1,RS_E_RPM_PC2,...,wind_speed,wind_deg,wind_gust,clouds_all,weather_id,weather_main,weather_description,weather_icon,lat,lon
0,181.0,2023-08-01 03:44:12,50.769818,3.872114,27.0,23.0,255.0,238.0,794.0,801.0,...,5.89,255.0,12.99,97.0,804.0,Clouds,overcast clouds,04n,50.769818,3.872114
1,143.0,2023-08-01 06:36:29,51.039993,3.693429,33.0,32.0,272.0,324.0,802.0,804.0,...,5.27,251.0,10.46,56.0,803.0,Clouds,broken clouds,04d,51.039993,3.693429
2,183.0,2023-08-24 06:53:54,50.742203,3.602035,31.0,33.0,234.0,182.0,799.0,802.0,...,1.34,80.0,2.68,95.0,804.0,Clouds,overcast clouds,04d,50.742203,3.602035
3,177.0,2023-08-01 13:53:38,50.930914,5.327132,35.0,38.0,220.0,244.0,794.0,801.0,...,6.17,270.0,NaN,75.0,803.0,Clouds,broken clouds,04d,50.930914,5.327132
4,143.0,2023-08-24 07:02:30,51.180773,3.575259,41.0,34.0,227.0,282.0,806.0,800.0,...,2.04,125.0,3.65,100.0,804.0,Clouds,overcast clouds,04d,51.180773,3.575259
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17679268,180.0,2023-05-28 19:28:59,50.919864,3.791125,40.0,36.0,238.0,238.0,800.0,797.0,...,6.02,33.0,10.80,51.0,803.0,Clouds,broken clouds,04d,50.919864,3.791125
17679269,180.0,2023-05-28 19:54:41,51.035243,3.710695,41.0,31.0,244.0,241.0,790.0,801.0,...,6.02,33.0,10.80,51.0,803.0,Clouds,broken clouds,04d,51.035243,3.710695
17679270,122.0,2023-05-28 20:23:20,51.015686,3.775316,52.0,42.0,3.0,3.0,0.0,0.0,...,6.20,33.0,11.94,39.0,802.0,Clouds,scattered clouds,03n,51.015686,3.775316
17679271,177.0,2023-05-28 20:46:00,51.189586,5.109380,27.0,38.0,417.0,469.0,1441.0,1454.0,...,6.21,33.0,12.24,19.0,801.0,Clouds,few clouds,02n,51.189586,5.109380
17679272,110.0,2023-05-28 21:05:24,51.041178,3.683947,37.0,33.0,220.0,196.0,805.0,796.0,...,6.72,36.0,13.00,32.0,802.0,Clouds,scattered clouds,03n,51.041178,3.683947

In [31]:
merged_df['lat'] = merged_df['lat_x']
merged_df['lon'] = merged_df['lon_x']

In [33]:
final_df = pd.merge(merged_df, df_3, on=['lat', 'lon'], how='left')
final_df

,mapped_veh_id,timestamps_UTC,lat_x,lon_x,RS_E_InAirTemp_PC1,RS_E_InAirTemp_PC2,RS_E_OilPress_PC1,RS_E_OilPress_PC2,RS_E_RPM_PC1,RS_E_RPM_PC2,...,clouds_all,weather_id,weather_main,weather_description,weather_icon,lat,lon,cell_lat,cell_lon,elevation
0,181.0,2023-08-01 03:44:12,50.769818,3.872114,27.0,23.0,255.0,238.0,794.0,801.0,...,97.0,804.0,Clouds,overcast clouds,04n,50.769818,3.872114,NaN,NaN,NaN
1,143.0,2023-08-01 06:36:29,51.039993,3.693429,33.0,32.0,272.0,324.0,802.0,804.0,...,56.0,803.0,Clouds,broken clouds,04d,51.039993,3.693429,NaN,NaN,NaN
2,183.0,2023-08-24 06:53:54,50.742203,3.602035,31.0,33.0,234.0,182.0,799.0,802.0,...,95.0,804.0,Clouds,overcast clouds,04d,50.742203,3.602035,NaN,NaN,NaN
3,177.0,2023-08-01 13:53:38,50.930914,5.327132,35.0,38.0,220.0,244.0,794.0,801.0,...,75.0,803.0,Clouds,broken clouds,04d,50.930914,5.327132,NaN,NaN,NaN
4,143.0,2023-08-24 07:02:30,51.180773,3.575259,41.0,34.0,227.0,282.0,806.0,800.0,...,100.0,804.0,Clouds,overcast clouds,04d,51.180773,3.575259,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17679268,180.0,2023-05-28 19:28:59,50.919864,3.791125,40.0,36.0,238.0,238.0,800.0,797.0,...,51.0,803.0,Clouds,broken clouds,04d,50.919864,3.791125,NaN,NaN,NaN
17679269,180.0,2023-05-28 19:54:41,51.035243,3.710695,41.0,31.0,244.0,241.0,790.0,801.0,...,51.0,803.0,Clouds,broken clouds,04d,51.035243,3.710695,NaN,NaN,NaN
17679270,122.0,2023-05-28 20:23:20,51.015686,3.775316,52.0,42.0,3.0,3.0,0.0,0.0,...,39.0,802.0,Clouds,scattered clouds,03n,51.015686,3.775316,NaN,NaN,NaN
17679271,177.0,2023-05-28 20:46:00,51.189586,5.109380,27.0,38.0,417.0,469.0,1441.0,1454.0,...,19.0,801.0,Clouds,few clouds,02n,51.189586,5.109380,NaN,NaN,NaN
17679272,110.0,2023-05-28 21:05:24,51.041178,3.683947,37.0,33.0,220.0,196.0,805.0,796.0,...,32.0,802.0,Clouds,scattered clouds,03n,51.041178,3.683947,NaN,NaN,NaN

In [ ]:
# 'mapped_veh_id', 'timestamps_UTC', 'lat_x', 'lon_x',
#        'RS_E_InAirTemp_PC1', 'RS_E_InAirTemp_PC2', 'RS_E_OilPress_PC1',
#        'RS_E_OilPress_PC2', 'RS_E_RPM_PC1', 'RS_E_RPM_PC2', 'RS_E_WatTemp_PC1',
#        'RS_E_WatTemp_PC2', 'RS_T_OilTemp_PC1', 'RS_T_OilTemp_PC2',
#        'date_hour_x', 'date', 'hour', 'date_hour_y', 'lat_y', 'lon_y', 'temp',
#        'main_feels_like', 'main_pressure', 'main_humidity', 'main_temp_min',
#        'main_temp_max', 'wind_speed', 'wind_deg', 'wind_gust', 'clouds_all',
#        'weather_id', 'weather_main', 'weather_description', 'weather_icon',
#        'lat', 'lon'],
#       dtype='object')
#- Rename the lat, lon
# - Drop unnecessary columns.

In [ ]:
final_df.rename(columns={'lat_x': 'lat'}, inplace=True)

In [45]:
result = final_df[(final_df['lat_x'] == 51.0163) & (final_df['lon_x'] == 3.7728)]
result

Empty DataFrame
Columns: [mapped_veh_id, timestamps_UTC, lat_x, lon_x, RS_E_InAirTemp_PC1, RS_E_InAirTemp_PC2, RS_E_OilPress_PC1, RS_E_OilPress_PC2, RS_E_RPM_PC1, RS_E_RPM_PC2, RS_E_WatTemp_PC1, RS_E_WatTemp_PC2, RS_T_OilTemp_PC1, RS_T_OilTemp_PC2, date_hour_x, date, hour, date_hour_y, lat_y, lon_y, temp, weather, weather_description]
Index: []

[0 rows x 23 columns]

In [43]:
result = final_df[final_df['lat_x'] == 50.001787]
result

Empty DataFrame
Columns: [mapped_veh_id, timestamps_UTC, lat_x, lon_x, RS_E_InAirTemp_PC1, RS_E_InAirTemp_PC2, RS_E_OilPress_PC1, RS_E_OilPress_PC2, RS_E_RPM_PC1, RS_E_RPM_PC2, RS_E_WatTemp_PC1, RS_E_WatTemp_PC2, RS_T_OilTemp_PC1, RS_T_OilTemp_PC2, date_hour_x, date, hour, date_hour_y, lat_y, lon_y, temp, weather, weather_description]
Index: []

[0 rows x 23 columns]

In [47]:
print(final_df['temp'])

0           288.190002
1           288.709991
2           291.380005
3           293.589996
4           292.709991
               ...
17679268    290.230011
17679269    290.230011
17679270    288.809998
17679271    291.420013
17679272    287.820007
Name: temp, Length: 17679273, dtype: Float32

In [48]:
final_df

,mapped_veh_id,timestamps_UTC,lat_x,lon_x,RS_E_InAirTemp_PC1,RS_E_InAirTemp_PC2,RS_E_OilPress_PC1,RS_E_OilPress_PC2,RS_E_RPM_PC1,RS_E_RPM_PC2,...,RS_T_OilTemp_PC2,date_hour_x,date,hour,date_hour_y,lat_y,lon_y,temp,weather,weather_description
0,181.0,2023-08-01 03:44:12,50.769818,3.872114,27.0,23.0,255.0,238.0,794.0,801.0,...,77.0,2023-08-01 03:00,2023-08-01,03:00,2023-08-01 03:00:00,50.7696,3.8720,288.190002,Clouds,overcast clouds
1,143.0,2023-08-01 06:36:29,51.039993,3.693429,33.0,32.0,272.0,324.0,802.0,804.0,...,74.0,2023-08-01 06:00,2023-08-01,06:00,2023-08-01 06:00:00,51.0392,3.6966,288.709991,Clouds,broken clouds
2,183.0,2023-08-24 06:53:54,50.742203,3.602035,31.0,33.0,234.0,182.0,799.0,802.0,...,87.0,2023-08-24 06:00,2023-08-24,06:00,2023-08-24 06:00:00,50.8538,3.6208,291.380005,Clouds,overcast clouds
3,177.0,2023-08-01 13:53:38,50.930914,5.327132,35.0,38.0,220.0,244.0,794.0,801.0,...,82.0,2023-08-01 13:00,2023-08-01,13:00,2023-08-01 13:00:00,51.0544,5.2561,293.589996,Clouds,broken clouds
4,143.0,2023-08-24 07:02:30,51.180773,3.575259,41.0,34.0,227.0,282.0,806.0,800.0,...,79.0,2023-08-24 07:00,2023-08-24,07:00,2023-08-24 07:00:00,51.0994,3.6720,292.709991,Clouds,overcast clouds
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17679268,180.0,2023-05-28 19:28:59,50.919864,3.791125,40.0,36.0,238.0,238.0,800.0,797.0,...,92.0,2023-05-28 19:00,2023-05-28,19:00,2023-05-28 19:00:00,50.9202,3.7960,290.230011,Clouds,broken clouds
17679269,180.0,2023-05-28 19:54:41,51.035243,3.710695,41.0,31.0,244.0,241.0,790.0,801.0,...,87.0,2023-05-28 19:00,2023-05-28,19:00,2023-05-28 19:00:00,50.9202,3.7960,290.230011,Clouds,broken clouds
17679270,122.0,2023-05-28 20:23:20,51.015686,3.775316,52.0,42.0,3.0,3.0,0.0,0.0,...,82.0,2023-05-28 20:00,2023-05-28,20:00,2023-05-28 20:00:00,51.0227,3.7524,288.809998,Clouds,scattered clouds
17679271,177.0,2023-05-28 20:46:00,51.189586,5.109380,27.0,38.0,417.0,469.0,1441.0,1454.0,...,80.0,2023-05-28 20:00,2023-05-28,20:00,2023-05-28 20:00:00,51.1571,5.1562,291.420013,Clouds,few clouds
17679272,110.0,2023-05-28 21:05:24,51.041178,3.683947,37.0,33.0,220.0,196.0,805.0,796.0,...,75.0,2023-05-28 21:00,2023-05-28,21:00,2023-05-28 21:00:00,51.0256,3.7420,287.820007,Clouds,scattered clouds

In [49]:
merged_df.columns  #temp, weather_main, 'weather_description', 'elevation'

Index(['mapped_veh_id', 'timestamps_UTC', 'lat_x', 'lon_x',
       'RS_E_InAirTemp_PC1', 'RS_E_InAirTemp_PC2', 'RS_E_OilPress_PC1',
       'RS_E_OilPress_PC2', 'RS_E_RPM_PC1', 'RS_E_RPM_PC2', 'RS_E_WatTemp_PC1',
       'RS_E_WatTemp_PC2', 'RS_T_OilTemp_PC1', 'RS_T_OilTemp_PC2',
       'date_hour_x', 'date', 'hour', 'date_hour_y', 'lat_y', 'lon_y', 'temp',
       'main_feels_like', 'main_pressure', 'main_humidity', 'main_temp_min',
       'main_temp_max', 'wind_speed', 'wind_deg', 'wind_gust', 'clouds_all',
       'weather_id', 'weather_main', 'weather_description', 'weather_icon',
       'lat', 'lon'],
      dtype='object')

In [ ]:
final_df['temp'] = final_df['temp'].astype('Float32')

# Rename 'weather_main' to 'weather'
final_df.rename(columns={'weather_main': 'weather'}, inplace=True)

In [50]:
final_df.columns

Index(['mapped_veh_id', 'timestamps_UTC', 'lat_x', 'lon_x',
       'RS_E_InAirTemp_PC1', 'RS_E_InAirTemp_PC2', 'RS_E_OilPress_PC1',
       'RS_E_OilPress_PC2', 'RS_E_RPM_PC1', 'RS_E_RPM_PC2', 'RS_E_WatTemp_PC1',
       'RS_E_WatTemp_PC2', 'RS_T_OilTemp_PC1', 'RS_T_OilTemp_PC2',
       'date_hour_x', 'date', 'hour', 'date_hour_y', 'lat_y', 'lon_y', 'temp',
       'weather', 'weather_description'],
      dtype='object')

In [57]:
final_df.drop('lon_y', axis=1, inplace=True)

In [58]:
final_df.columns

Index(['mapped_veh_id', 'timestamps_UTC', 'lat_x', 'lon_x',
       'RS_E_InAirTemp_PC1', 'RS_E_InAirTemp_PC2', 'RS_E_OilPress_PC1',
       'RS_E_OilPress_PC2', 'RS_E_RPM_PC1', 'RS_E_RPM_PC2', 'RS_E_WatTemp_PC1',
       'RS_E_WatTemp_PC2', 'RS_T_OilTemp_PC1', 'RS_T_OilTemp_PC2', 'temp',
       'weather', 'weather_description'],
      dtype='object')

In [62]:
final_df.rename(columns={'lon_x': 'lon'}, inplace=True)
final_df.head()

,mapped_veh_id,timestamps_UTC,lat,lon,RS_E_InAirTemp_PC1,RS_E_InAirTemp_PC2,RS_E_OilPress_PC1,RS_E_OilPress_PC2,RS_E_RPM_PC1,RS_E_RPM_PC2,RS_E_WatTemp_PC1,RS_E_WatTemp_PC2,RS_T_OilTemp_PC1,RS_T_OilTemp_PC2,temp,weather,weather_description
0,181.0,2023-08-01 03:44:12,50.769818,3.872114,27.0,23.0,255.0,238.0,794.0,801.0,83.0,81.0,76.0,77.0,288.190002,Clouds,overcast clouds
1,143.0,2023-08-01 06:36:29,51.039993,3.693429,33.0,32.0,272.0,324.0,802.0,804.0,78.0,78.0,73.0,74.0,288.709991,Clouds,broken clouds
2,183.0,2023-08-24 06:53:54,50.742203,3.602035,31.0,33.0,234.0,182.0,799.0,802.0,82.0,82.0,85.0,87.0,291.380005,Clouds,overcast clouds
3,177.0,2023-08-01 13:53:38,50.930914,5.327132,35.0,38.0,220.0,244.0,794.0,801.0,77.0,81.0,78.0,82.0,293.589996,Clouds,broken clouds
4,143.0,2023-08-24 07:02:30,51.180773,3.575259,41.0,34.0,227.0,282.0,806.0,800.0,85.0,78.0,82.0,79.0,292.709991,Clouds,overcast clouds

In [63]:
df_1 = pd.read_csv('ar41_for_ulb.csv')

In [66]:
df_1.columns

Index(['mapped_veh_id', 'timestamps_UTC', 'lat_x', 'lon_x',
       'RS_E_InAirTemp_PC1', 'RS_E_InAirTemp_PC2', 'RS_E_OilPress_PC1',
       'RS_E_OilPress_PC2', 'RS_E_RPM_PC1', 'RS_E_RPM_PC2', 'RS_E_WatTemp_PC1',
       'RS_E_WatTemp_PC2', 'RS_T_OilTemp_PC1', 'RS_T_OilTemp_PC2',
       'date_hour_x', 'date', 'hour', 'date_hour_y', 'lat_y', 'lon_y', 'temp',
       'main_feels_like', 'main_pressure', 'main_humidity', 'main_temp_min',
       'main_temp_max', 'wind_speed', 'wind_deg', 'wind_gust', 'clouds_all',
       'weather_id', 'weather_main', 'weather_description', 'weather_icon'],
      dtype='object')

In [67]:
columns_to_drop = ['date_hour_x', 'date', 'hour', 'date_hour_y', 'lat_y', 'lon_y', 'main_feels_like', 'main_pressure', 'main_humidity', 'main_temp_min',
       'main_temp_max', 'wind_speed', 'wind_deg', 'wind_gust', 'clouds_all', 'weather_id', 'weather_icon']
df_dropped = df_1.drop(columns=columns_to_drop)

In [69]:
df_dropped.head()

,mapped_veh_id,timestamps_UTC,lat_x,lon_x,RS_E_InAirTemp_PC1,RS_E_InAirTemp_PC2,RS_E_OilPress_PC1,RS_E_OilPress_PC2,RS_E_RPM_PC1,RS_E_RPM_PC2,RS_E_WatTemp_PC1,RS_E_WatTemp_PC2,RS_T_OilTemp_PC1,RS_T_OilTemp_PC2,temp,weather_main,weather_description
0,181.0,2023-08-01 03:44:12,50.769818,3.872114,27.0,23.0,255.0,238.0,794.0,801.0,83.0,81.0,76.0,77.0,288.19,Clouds,overcast clouds
1,143.0,2023-08-01 06:36:29,51.039993,3.693429,33.0,32.0,272.0,324.0,802.0,804.0,78.0,78.0,73.0,74.0,288.71,Clouds,broken clouds
2,183.0,2023-08-24 06:53:54,50.742203,3.602035,31.0,33.0,234.0,182.0,799.0,802.0,82.0,82.0,85.0,87.0,291.38,Clouds,overcast clouds
3,177.0,2023-08-01 13:53:38,50.930914,5.327132,35.0,38.0,220.0,244.0,794.0,801.0,77.0,81.0,78.0,82.0,293.59,Clouds,broken clouds
4,143.0,2023-08-24 07:02:30,51.180773,3.575259,41.0,34.0,227.0,282.0,806.0,800.0,85.0,78.0,82.0,79.0,292.71,Clouds,overcast clouds

In [70]:
final_df.to_csv('final.csv', index=False)

In [2]:
import pandas as pd
final_df = pd.read_csv('final.csv')
final_df.isna().sum()

mapped_veh_id              0
timestamps_UTC             0
lat                        0
lon                        0
RS_E_InAirTemp_PC1         0
RS_E_InAirTemp_PC2     12726
RS_E_OilPress_PC1          0
RS_E_OilPress_PC2      12726
RS_E_RPM_PC1               0
RS_E_RPM_PC2           12726
RS_E_WatTemp_PC1           0
RS_E_WatTemp_PC2       12726
RS_T_OilTemp_PC1           0
RS_T_OilTemp_PC2       12726
temp                    4853
weather                 4853
weather_description     4853
dtype: int64