In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('grouped2.csv')
df

,mapped_veh_id,timestamps_UTC,lat,lon,RS_E_InAirTemp_PC1,RS_E_InAirTemp_PC2,RS_E_OilPress_PC1,RS_E_OilPress_PC2,RS_E_RPM_PC1,RS_E_RPM_PC2,...,main_temp_max,wind_speed,wind_deg,wind_gust,clouds_all,weather_id,weather_main,weather_description,weather_icon,elevation
0,181.0,2023-08-01 03:44:12,50.769818,3.872114,27.0,23.0,255.0,238.0,794.0,801.0,...,288.74,5.89,255.0,12.99,97.0,804.0,Clouds,overcast clouds,04n,23.0
1,143.0,2023-08-01 06:36:29,51.039993,3.693429,33.0,32.0,272.0,324.0,802.0,804.0,...,289.32,5.27,251.0,10.46,56.0,803.0,Clouds,broken clouds,04d,8.0
2,183.0,2023-08-24 06:53:54,50.742203,3.602035,31.0,33.0,234.0,182.0,799.0,802.0,...,292.38,1.34,80.0,2.68,95.0,804.0,Clouds,overcast clouds,04d,47.0
3,177.0,2023-08-01 13:53:38,50.930914,5.327132,35.0,38.0,220.0,244.0,794.0,801.0,...,294.83,6.17,270.0,NaN,75.0,803.0,Clouds,broken clouds,04d,37.0
4,143.0,2023-08-24 07:02:30,51.180773,3.575259,41.0,34.0,227.0,282.0,806.0,800.0,...,294.29,2.04,125.0,3.65,100.0,804.0,Clouds,overcast clouds,04d,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18247450,180.0,2023-05-28 19:28:59,50.919864,3.791125,40.0,36.0,238.0,238.0,800.0,797.0,...,293.73,6.02,33.0,10.80,51.0,803.0,Clouds,broken clouds,04d,44.0
18247451,180.0,2023-05-28 19:54:41,51.035243,3.710695,41.0,31.0,244.0,241.0,790.0,801.0,...,293.73,6.02,33.0,10.80,51.0,803.0,Clouds,broken clouds,04d,7.0
18247452,122.0,2023-05-28 20:23:20,51.015686,3.775316,52.0,42.0,3.0,3.0,0.0,0.0,...,291.20,6.20,33.0,11.94,39.0,802.0,Clouds,scattered clouds,03n,10.0
18247453,177.0,2023-05-28 20:46:00,51.189586,5.109380,27.0,38.0,417.0,469.0,1441.0,1454.0,...,292.29,6.21,33.0,12.24,19.0,801.0,Clouds,few clouds,02n,26.0
18247454,110.0,2023-05-28 21:05:24,51.041178,3.683947,37.0,33.0,220.0,196.0,805.0,796.0,...,290.19,6.72,36.0,13.00,32.0,802.0,Clouds,scattered clouds,03n,4.0

In [4]:
duplicate_rows_df = df[df.duplicated()]
print("number of duplicate rows: ", duplicate_rows_df.shape)

number of duplicate rows:  (580912, 29)

In [5]:
df = df.drop_duplicates()

In [6]:
duplicate_rows_df = df[df.duplicated()]
print("number of duplicate rows: ", duplicate_rows_df.shape)

number of duplicate rows:  (0, 29)